service: home-hub-interaction-model

provider:
  name: aws
  runtime: python3.7

  stage: dev
  region: us-east-1

  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - "arn:aws:dynamodb:us-east-1:982689203849:table/${self:provider.environment.TableName}"

  environment:
    TableName:
      'Fn::ImportValue': 'DynamoDbTableName-dev'


functions:
  lambda:
    handler: handler.handle

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stage: ${opt:stage, self:provider.stage}