version: 2
jobs:
  dev_build_deploy_skill_lambda:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs13-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build skill lambda
          command: |
            cd skill-lambda && npm i -g serverless && npm i
      - run:
          name: dev deploy skill lambda
          command: cd skill-lambda && serverless deploy --stage dev

  prod_build_deploy_skill_lambda:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs13-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build skill lambda
          command: |
            cd skill-lambda && npm i -g serverless && npm i
      - run:
          name: dev deploy skill lambda
          command: cd skill-lambda && serverless deploy --stage prod

  dev_build_interaction_model_lambda:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs13-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build interaction model lambda
          command: |
            cd interaction-model && npm i -g serverless && npm i
      - run:
          name: dev deploy interaction model lambda
          command: cd interaction-model && serverless deploy --stage dev

  prod_build_interaction_model_lambda:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs13-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build interaction model lambda
          command: |
            cd interaction-model && npm i -g serverless && npm i
      - run:
          name: dev deploy interaction model lambda
          command: cd interaction-model && serverless deploy --stage prod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - dev_build_deploy_skill_lambda:
          context: home-hub-deploy
      - prod_build_deploy_skill_lambda:
          context: home-hub-deploy
          type: approval
          requires:
            - dev_build_deploy_skill_lambda
      - dev_build_interaction_model_lambda:
          context: home-hub-deploy
      - prod_build_interaction_model_lambda:
          context: home-hub-deploy
          type: approval
          requires:
            - dev_build_interaction_model_lambda
