# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_skill_lambda
      - build_interaction_model_lambda

jobs:
  build_skill_lambda:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: pip3 install pipenv

      - run:
          name: build skill lambda
          command: |
            cd skill-lambda && pipenv install && npm install && npm i -g serverless  && serverless deploy

  build_interaction_model_lambda:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: pipenv install

      - run:
          name: build interaction model lambda
          command: |
            cd interaction-model && npm install && npm i -g serverless  && serverless deploy