# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_skill_lambda:
    docker:
      - image: nikolaik/python-nodejs

    working_directory: ~/repo

    steps:
      - checkout

      - run:
         command: |
           cd skill-lambda
           add-apt-repository universe
           apt update
           apt install python-pip
           pipenv install

      - run:
          name: build skill lambda
          command: |
            cd skill-lambda && npm install && npm i -g serverless  && serverless deploy

  build_interaction_model_lambda:
    docker:
      - image: nikolaik/python-nodejs

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            cd interaction-model
            add-apt-repository universe
            apt update
            apt install python-pip
            pipenv install

      - run:
          name: build interaction model lambda
          command: |
            cd interaction-model && npm install && npm i -g serverless && serverless deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_skill_lambda:
          context: home-hub-deploy
      - build_interaction_model_lambda:
          context: home-hub-deploy