Resources:
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: group_id
          AttributeType: S
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: group_id
          KeyType: HASH
        - AttributeName: device_id
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
Outputs:
  DynamoTableName:
    Value: ${self:custom.tableName}
    Export:
      Name: DynamoDbTableName-${opt:stage, self:provider.stage}